# Default configuration for MemCP server

[graphiti]
    group_id            = ""                      # Optional, will be generated if not provided
    model_name          = ""                      # Optional
    neo4j_password      = "password"
    neo4j_uri           = "bolt://localhost:7687"
    neo4j_user          = "neo4j"
    openai_api_key      = ""                      # Set via environment variable
    openai_base_url     = ""                      # Optional
    use_custom_entities = false

[mcp]
    instructions_template_name = "default_instructions"
    templates_dir              = ""
    transport                  = "sse"

[logging]
    backup_count     = 5
    file_path        = ""                                                     # Optional, logs to console by default
    format           = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    level            = "INFO"
    log_to_console   = true
    log_to_file      = false
    max_file_size    = 10485760                                               # 10MB
    rich_tracebacks  = true
    use_rich_console = true
