# MemCP Configuration File (example.config.toml)
# Copy this file to config.toml and customize as needed


# fill in all of the defaults from settings.py
[neo4j]
    uri  = "bolt://localhost:7687"
    user = "neo4j"
    # DO NOT set password here - use environment variables!

[openai]
    # DO NOT set api_key here - use environment variables!
    # Optional, set if using a custom OpenAI endpoint
    # base_url = "https://api.example.com"  
    model_name = "gpt-4o-mini"

[graph]
    # If not specified, a random ID will be generated
    # id = "my-graph-id"
    use_memcp_entities = false

[server]
    host      = "127.0.0.1"
    port      = 8000
    transport = "sse"

[mcp]
    instructions = "memcp/instructions/mcp_instructions.py"
    name         = "memcp"
